spring:
  application:
    name: switch
  el-util:
    zookeeper:
      namespace: switch/application
      base-sleep-time-ms: 20
      root-path: root
      server-addr: localhost:2181
      enable: true
      max-retries: 3
      digest: rt:rt
      sessionTimeoutMs: 50000
      connection-timeout-ms: 40000